### ISSUE TITLE
Feature Request: match_all

### ISSUE THREAD

**Issue by 0racle** [AlexP007/regex-object#1]
This module is quite similar to something I built to use internally at work. This module is a little nicer, but one feature my module had - and one of the main reasons I built it - was to make doing `qr/.../g` captures easier (ie. by abstracting away the while loop).

A `match_all` method could be trivially added to this module, allowing this sort of thing

```perl
my $re = Regex::Object->new(regex => qr/(?<name>\w+?) (?<surname>\w+)/);
my @names = { $_->match } $re->match_all('John Doe Eric Lide Hans Zimmermann');
````

Then `@names` would contain

````
[
    [0] "John Doe",
    [1] "Eric Lide",
    [2] "Hans Zimmermann"
]
````

Thoughts?

**Comment by AlexP007** [comment]
Like this idea.
Sketched some code here -> https://github.com/AlexP007/regex-object/tree/feature-match-all

```
use strict;
use warnings;

use Regex::Object;
use Data::Dumper;

my $re = Regex::Object->new(regex => qr/(?<name>\w+?) (?<surname>\w+)/);

my $match_all = $re->match_all('John Doe Eric Lide Hans Zimmermann');

print Dumper($match_all->match_all);
print Dumper($match_all->captures_all);
```
If you want to improve or add something, please let me know!

**Comment by 0racle** [comment]
Looks good.

**Comment by AlexP007** [comment]
implemented https://github.com/AlexP007/regex-object/releases/tag/1.20
